# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.1.1+26.2
maven_group=mnfu
archives_base_name=ClanTag
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.153.0+26.2
# https://maven.nucleoid.xyz/eu/pb4/placeholder-api/
placeholder_api_version=3.1.0-beta.1+26.2
sqlite_jdbc_version=3.51.2.0
fabric_permissions_api=0.7.0